name: Test

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install Swift Development Snapshot
        uses: slashmo/install-swift@v0.4.0
        with:
          version: swift-DEVELOPMENT-SNAPSHOT-2023-04-27-a
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Test
        run: swift test -v
